// What to shoot for each project page, and how to get each site into that state.
// shot: { id, url?, device?, boot?, fresh?, steps: [[op, ...args]], settle?, cursor?, focus?, alt }
//   ops: ['to', 'text=…' | css, frac]  scroll until that element's top sits at frac of the viewport
//        ['y', px] · ['wheel', dy, times] · ['click', sel] · ['hover', sel] · ['mouse', fx, fy] · ['tap', fx, fy]
//        ['drag', [x0, y0, x1, y1]] (fractions) · ['key', k] · ['wait', ms] · ['eval', fn]
// cover: shot id for the 16:9 cover · rows: [['full'|'pair'|'trio', ...shot ids]] (pair = two frames side by side)
// focus: [fx, fy] centre of the crop if a row's aspect ever differs from the capture (all rows are 16:9 or phone now)
// devices: wide 1600x900@2 · mid 1440x810@2.22 · narrow 1280x720@2.5 · phone 414x670@3 (tools/shots.mjs)
// Picks came from a full top-to-bottom survey of every site, desktop and phone (half-viewport steps).
// Shots not named in cover/rows are alternates, or steps that bring the page into the next shot's state.

const P = 'phone';
// lazy images: load everything up front so no frame catches a blurred placeholder
const EAGER = [['eval', () => document.querySelectorAll('img[loading="lazy"]').forEach((i) => { i.loading = 'eager'; })], ['wait', 3500]];

// the scripted demo under the hero loops every ~13 s; wait for the frame where Awan has ringed week 9 and answered
// (the answer stays up through the agent step, so wait for a fresh cycle first)
const DEMO_REPLY = [['eval', () => new Promise((done) => {
  const d = document.querySelector('#demo'); let fresh = false;
  const t = () => { if (!d.classList.contains('reply')) fresh = true; if (fresh && d.classList.contains('reply')) done(); else setTimeout(t, 40); }; t();
})], ['wait', 900]];

// FF Member's intro: catch the card mid-issue, the counter past halfway and a status line up
const INTRO_MID = [['eval', () => new Promise((done) => {
  const t = () => { const c = document.querySelector('[data-intro-count]'); if (!c || +c.textContent >= 70) done(); else setTimeout(t, 20); }; t();
})]];

export const RECIPES = {
  'hai-awan': {
    base: 'https://awan.ffdev.studio/', device: 'mid', boot: 2500, settle: 1200,
    shots: [
      { id: 'hero', steps: DEMO_REPLY, alt: 'hai awan: the headline among app screenshots and stickers, the demo below answering about week 9' },
      { id: 'demo', steps: [['to', '#demo', 0.1], ...DEMO_REPLY], alt: 'The demo: Awan has flown to the week 9 bar in a chart, circled it and answered' },
      { id: 'learn', steps: [['to', '.feat-row >> nth=0', 0.21]], settle: 6500, alt: 'Finally learn the thing: asked how to total a column, Awan points at the cell and writes the formula' },
      { id: 'context', steps: [['to', '.feat-row >> nth=1', 0.21]], settle: 6500, alt: 'Your screen is the context: why won’t this import? — Awan rings the bad date column' },
      { id: 'agents', steps: [['to', '.feat-row >> nth=2', 0.21]], settle: 6500, alt: 'Hand off work with your voice: an Awan agent starts on the weekly report' },
      { id: 'idea', steps: [['to', '#idea', 0.0]], settle: 5000, alt: 'The idea, typed out on a note between rainbow arches of little clouds' },
      { id: 'asks', steps: [['to', '#asks-title', 0.3]], settle: 2500, alt: 'Ask it anything: a wall of real questions, and the line that Hai Awan is fully open source' },
      { id: 'pricing', steps: [['to', '#pr-title', 0.1]], settle: 2500, alt: 'Pricing under a cloudy sky: free, pro and max' },
      { id: 'faq', steps: [['to', '#faq-title', 0.2]], alt: 'Frequently asked questions, starting with what Hai Awan is and whether it is open source' },
      { id: 'footer', steps: [['y', 99999]], settle: 2500, alt: 'The footer: the Hai Awan wordmark drawn in little clouds' },
      { id: 'm-hero', device: P, steps: DEMO_REPLY, alt: 'Phone: the hero' },
      { id: 'm-learn', device: P, steps: [['to', '.feat-row >> nth=0', 0.12]], settle: 6500, alt: 'Phone: Awan pointing at a spreadsheet' },
      { id: 'm-pricing', device: P, steps: [['to', '#pr-title', 0.08]], settle: 2500, alt: 'Phone: pricing under the clouds' },
    ],
    cover: 'hero',
    rows: [['full', 'demo'], ['pair', 'learn', 'context'], ['trio', 'm-hero', 'm-learn', 'm-pricing'], ['full', 'agents'], ['full', 'idea'], ['full', 'pricing'], ['pair', 'asks', 'faq']],
  },

  // the hero is a 440vh scrubbed scroll: the table card's QR scatters, its modules become a mosaic of the photos,
  // then the real gallery resolves. Offsets are at 1440x810 (the hero's scrub has to settle before each frame).
  'indahnya': {
    base: 'https://indahnya-86v.pages.dev/', device: 'mid', boot: 5000, settle: 2200, init: EAGER,
    shots: [
      { id: 'hero', steps: [['wait', 3000]], alt: 'Semua gambar majlis. Satu QR. — the table card with its QR among floating polaroids, guests’ uploads arriving below' },
      { id: 'scatter', steps: [['y', 1215]], settle: 2800, alt: 'The hero scrolling: the QR’s modules breaking away from the code' },
      { id: 'mosaic', steps: [['y', 1900]], settle: 2800, alt: 'The modules land as a mosaic, each taking the colour of its spot in a guest’s photo' },
      { id: 'gallery', steps: [['y', 2835]], settle: 2800, alt: 'The real gallery resolves: the majlis photos, with Aina & Hakim’s gallery bar' },
      { id: 'story', steps: [['y', 3700]], alt: 'Makcik snap dari meja empat — the apps and group chats it replaces, struck through' },
      { id: 'how', steps: [['y', 4860]], settle: 2800, alt: 'Tiga langkah: a guest scans the table card and uploads from the phone' },
      { id: 'dewan', steps: [['y', 7695]], settle: 3000, alt: 'Lampu malap. Gambar naik. — the page dims like the dewan and the slideshow fills the TV' },
      { id: 'kad', steps: [['to', '#kad', 0.0]], settle: 2500, alt: 'Kad jemputan yang orang betul-betul buka: the e-kad on a phone, with its template picker' },
      { id: 'guests', steps: [['y', 10125]], alt: 'Sebelum majlis, tetamu dah tahu semua: RSVP count and the seat finder on a floor plan' },
      { id: 'host', steps: [['y', 11450]], settle: 3000, alt: 'Dari atas pelamin pun boleh urus: the host filters photos before they reach the screen' },
      { id: 'pricing', steps: [['to', '#harga', 0.0]], settle: 2500, alt: 'Bayar sekali. Untuk satu majlis. — Percuma, RM59 and RM99, one time' },
      { id: 'faq', steps: [['to', '#soalan', 0.0]], alt: 'Yang orang selalu tanya: the FAQ' },
      { id: 'footer', steps: [['y', 99999]], settle: 3000, alt: 'The footer: the indahnya wordmark filled with majlis photos, the vine’s roots under it' },
      { id: 'sample', url: 'aina-hakim/gambar', steps: [['wait', 3000]], alt: 'The sample majlis: Aina & Hakim’s guest gallery' },
      { id: 'm-hero', device: P, steps: [['wait', 3000]], alt: 'Phone: the hero, the table card waiting under the buttons' },
      { id: 'm-gallery', device: P, steps: [['y', 1900]], settle: 2800, alt: 'Phone: the gallery the QR turns into' },
      { id: 'm-pricing', device: P, steps: [['y', 13300]], settle: 2500, alt: 'Phone: one-time pricing, RM59 most picked' },
      { id: 'm-kad', device: P, steps: [['y', 7420]], settle: 2500, alt: 'Phone: the e-kad' },
    ],
    cover: 'hero',
    rows: [['full', 'gallery'], ['pair', 'scatter', 'mosaic'], ['trio', 'm-hero', 'm-gallery', 'm-kad'], ['full', 'how'], ['full', 'dewan'], ['pair', 'story', 'kad'], ['pair', 'guests', 'host'], ['full', 'pricing'], ['pair', 'sample', 'footer']],
  },

  // the intro issues the member card and covers every load (full on the first visit, a quick "Welcome back" after),
  // so the first shot in each context catches it mid-issue and the later pages boot long enough for it to hand off
  'ff-member': {
    base: 'https://ff-member.pages.dev/', device: 'mid', boot: 9000, settle: 1800,
    shots: [
      { id: 'intro', boot: 0, steps: INTRO_MID, settle: 0, alt: 'The intro: the member card being issued in the dark, a status line ticking through what membership covers' },
      { id: 'hero', fresh: true, steps: [], alt: 'Built by us. Looked after by us. — the black member card on a chrome plinth against a lit rock wall' },
      { id: 'globe', steps: [['y', 800]], settle: 4500, alt: 'Built in Kuala Lumpur. Kept online everywhere. — the night side of the globe, with backups, SSL and security updates landing' },
      { id: 'tube', steps: [['y', 2835]], settle: 2500, alt: 'One card for every site we look after: the card inside a turning tube of the studio’s work' },
      { id: 'figures', steps: [['y', 4455]], settle: 1200, alt: 'Plain terms, written down: the plan figures scrubbing past on bone' },
      { id: 'support', steps: [['y', 5950]], settle: 2500, alt: 'Priority support. A person, not a ticket. — over a tilted screen of SmoothSail' },
      { id: 'covers', steps: [['to', '#covers-title', 0.12]], settle: 2500, alt: 'Made for the sites we already built: hosting, monitoring, backups, security, changes and advice' },
      { id: 'banner', steps: [['to', '#banner-title', 0.3]], settle: 3500, alt: 'Three plans. One standard. — over a Big Brain Furniture interior' },
      { id: 'plans', device: 'wide', steps: [['to', '#plans-title', 0.1]], settle: 2500, alt: 'Choose how much we carry: Care RM59, Maintain RM149 and Evolve RM299 a month' },
      { id: 'join', steps: [['y', 0], ['click', '[data-join] >> nth=0']], settle: 1500, alt: 'The Become a member dialog: name, email, website and plan' },
      { id: 'footer', fresh: true, steps: [['y', 99999]], settle: 2500, alt: 'Launch is day one — the footer under the //FF mark' },
      { id: 'm-hero', device: P, boot: 10000, steps: [], alt: 'Phone: the member card on its plinth' },
      { id: 'm-tube', device: P, steps: [['to', '#tube-title', 0.55]], settle: 2500, alt: 'Phone: the card in the tube of work' },
      { id: 'm-plans', device: P, steps: [['to', '.plans .h3 >> nth=1', 0.2]], settle: 2500, alt: 'Phone: the Maintain plan' },
    ],
    cover: 'hero',
    rows: [['full', 'intro'], ['pair', 'globe', 'tube'], ['trio', 'm-hero', 'm-tube', 'm-plans'], ['full', 'figures'], ['full', 'support'], ['pair', 'covers', 'banner'], ['full', 'plans'], ['pair', 'join', 'footer']],
  },

  'ff-search': {
    base: 'https://ff-search-b4q.pages.dev/', device: 'mid', boot: 6000,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'The hero: the FF mark over a halftone field, the studio line in a mint panel' },
      { id: 'built', steps: [['y', 700]], alt: 'BUILT PROPERLY. set large in the grid' },
      { id: 'stats', steps: [['to', 'text=60+', 0.25]], settle: 3500, focus: [0.3, 0.5], alt: 'The numbers: RM1K–5K on mint, 60+ builds on black' },
      { id: 'services', steps: [['to', 'text=Built by', 0.02]], focus: [0.77, 0.5], alt: 'Services on black, each with a wireframe globe' },
      { id: 'clients', steps: [['to', '#clients', 0.0]], focus: [0.25, 0.5], alt: 'The Clients index' },
      { id: 'team2', steps: [['to', '#team', 0.0], ['wheel', 400, 1]], alt: 'The team: black-and-white portraits under role tags' },
      { id: 'cta', steps: [['to', "text=LET'S", 0.3]], alt: 'LET’S START A CONVERSATION in knocked-out type over the halftone' },
      { id: 'footer', steps: [['y', 99999]], focus: [0.3, 0.5], alt: 'The footer: the //FF Dev Studio lockup' },
      { id: 'dark', steps: [['y', 0], ['click', 'button[aria-label="Toggle theme"]'], ['wait', 4000]], alt: 'The hero in the dark theme' },
      { id: 'dark-stats', steps: [['to', 'text=60+', 0.25]], settle: 3500, alt: 'The numbers in the dark theme' },
      { id: 'm-built', device: P, steps: [['wheel', 350, 2]], alt: 'Phone: BUILT PROPERLY.' },
      { id: 'm-stats', device: P, steps: [['to', 'text=RM1K', 0.1]], settle: 3500, alt: 'Phone: the numbers' },
      { id: 'm-team', device: P, steps: [['to', 'text=Nur Aisyah', 0.75]], alt: 'Phone: a team portrait' },
    ],
    cover: 'hero',
    rows: [['full', 'built'], ['pair', 'stats', 'services'], ['trio', 'm-built', 'm-stats', 'm-team'], ['full', 'dark'], ['full', 'team2'], ['pair', 'clients', 'footer'], ['full', 'cta']],
  },

  'ff-stanzza': {
    base: 'https://ff-stanzza.pages.dev/', device: 'wide', boot: 7000,
    shots: [
      { id: 'hero', steps: [['wait', 2000]], alt: 'The hero: a warm living room under the demo notice' },
      { id: 'compose', steps: [['y', 1350]], alt: 'A home is a composition — photographs gathering around the line' },
      { id: 'pau', steps: [['y', 3600]], alt: 'Pau Claris Apartment on olive green, with the project’s facts' },
      { id: 'valencia', steps: [['y', 5400]], alt: 'Valencia apartment, the next project sliding in' },
      { id: 'people', steps: [['y', 6300]], alt: 'Controlled delivery: the lead and the process in black and white' },
      { id: 'navy', steps: [['y', 8550]], alt: 'Architectural thinking. Design sensibility. Premium delivery. — line drawings on navy' },
      { id: 'cards', steps: [['y', 11700]], alt: 'Architecture and Design cards passing on the horizontal track' },
      { id: 'about', steps: [['y', 15300]], alt: 'About us: 10 years in Spain over the Sagrada Família' },
      { id: 'about2', focus: [0.87, 0.5], steps: [['y', 19800]], alt: 'About us: 182 projects worldwide' },
      { id: 'blog', focus: [0.3, 0.5], steps: [['y', 21600]], alt: 'The blog: Barcelona Pavilion and L’Atelier' },
      { id: 'quote', steps: [['y', 23400]], alt: 'The founder’s line: good design feels inevitable' },
      { id: 'footer', steps: [['y', 99999]], alt: 'The footer’s pencil drawing of a pavilion' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-pau', device: P, steps: [['y', 3015]], alt: 'Phone: Pau Claris on green' },
      { id: 'm-valencia', device: P, steps: [['y', 4623]], alt: 'Phone: Valencia apartment' },
      { id: 'm-lead', device: P, steps: [['y', 5427]], alt: 'Phone: the responsible lead' },
      { id: 'm-navy', device: P, steps: [['y', 7638]], alt: 'Phone: architectural thinking on navy' },
      { id: 'm-design', device: P, steps: [['y', 9648]], alt: 'Phone: the Design card' },
      { id: 'm-about', device: P, steps: [['y', 12060]], alt: 'Phone: 10 years in Spain' },
    ],
    cover: 'hero',
    rows: [['full', 'pau'], ['full', 'navy'], ['trio', 'm-hero', 'm-pau', 'm-navy'], ['full', 'cards'], ['pair', 'blog', 'about2'], ['full', 'about'], ['trio', 'm-lead', 'm-design', 'm-about'], ['full', 'footer']],
  },

  'sunlight-supplies': {
    base: 'https://ff-sunlight.pages.dev/', device: 'narrow', boot: 5000,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'Racking, from the site survey up — the hero over a live 3D rack' },
      { id: 'stage-a', focus: [0.66, 0.5], steps: [['to', 'text=Six stages', 0.12], ['wheel', 400, 3]], settle: 2500, alt: 'Six stages: the frames standing' },
      { id: 'stage-b', steps: [['wheel', 400, 3]], settle: 2500, alt: 'Six stages: beams hung' },
      { id: 'stage-c', focus: [0.66, 0.5], steps: [['wheel', 400, 1], ['wait', 800], ['wheel', 250, 1], ['wait', 800], ['wheel', 200, 1]], settle: 5000, alt: 'Six stages: loaded out' },
      { id: 'systems', steps: [['to', 'text=Eighteen systems', 0.1]], alt: 'Eighteen systems, with installed photographs' },
      { id: 'installed', steps: [['to', 'text=Racking that is already', 0.16]], alt: 'Racking that is already standing in Johor' },
      { id: 'installed2', steps: [['wheel', 400, 1]], alt: 'Installed work: orange and blue racking in warehouses' },
      { id: 'retail', steps: [['to', 'text=The other half', 0.08]], alt: 'The other half of the business: shop-floor fixtures' },
      { id: 'process', steps: [['to', 'text=Nothing gets quoted', 0.1]], alt: 'Nothing gets quoted before it gets drawn' },
      { id: 'counters', steps: [['to', 'text=Three counters in Johor', 0.15]], alt: 'Three counters in Johor Bahru' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-stage', device: P, steps: [['to', 'text=Six stages', 0.35], ['wheel', 300, 8]], settle: 2500, alt: 'Phone: a rack stage' },
      { id: 'm-installed', device: P, steps: [['to', 'text=Racking that is already', 0.05], ['wheel', 300, 1]], alt: 'Phone: installed work' },
      { id: 'm-retail', device: P, steps: [['to', 'text=The other half', 0.05], ['wheel', 300, 1]], alt: 'Phone: shop-floor fixtures' },
      { id: 'm-counters', device: P, steps: [['to', 'text=Three counters in Johor', 0.14]], alt: 'Phone: the counters' },
    ],
    cover: 'hero',
    rows: [['full', 'stage-b'], ['pair', 'stage-a', 'stage-c'], ['trio', 'm-hero', 'm-stage', 'm-installed'], ['full', 'systems'], ['full', 'installed'], ['full', 'retail'], ['full', 'counters']],
  },

  'lewix-ai': {
    base: 'https://lewix.ai/', device: 'wide', boot: 10000,
    shots: [
      { id: 'loader', boot: 1800, fresh: true, steps: [], settle: 0, alt: 'The loader: the Lewix mark filling' },
      { id: 'hero', fresh: true, steps: [['wait', 1500]], alt: 'LEWIX over the particle mountain' },
      { id: 'mountain', steps: [['y', 1350]], alt: 'The camera climbing the particle mountain' },
      { id: 'mountain2', steps: [['y', 1800]], alt: 'The ridge, close' },
      { id: 'about', steps: [['y', 3600]], alt: '01 About' },
      { id: 'team', steps: [['y', 5700]], alt: '03 Founding Team: each founder as a particle figure' },
      { id: 'work', steps: [['y', 6750]], alt: '04 Work: the systems in production' },
      { id: 'contact', steps: [['y', 8100]], alt: '05 Contact' },
      { id: 'footer', steps: [['y', 99999]], alt: 'The footer: LEWIX over the mountain' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-about', device: P, steps: [['y', 2814]], alt: 'Phone: About' },
      { id: 'm-lewis', device: P, steps: [['y', 5829]], alt: 'Phone: a founder as a particle figure' },
      { id: 'm-noel', device: P, steps: [['y', 6231]], alt: 'Phone: a founder as a particle figure' },
      { id: 'm-work', device: P, steps: [['y', 7638]], alt: 'Phone: the work list' },
    ],
    cover: 'hero',
    rows: [['full', 'mountain'], ['pair', 'loader', 'mountain2'], ['trio', 'm-hero', 'm-lewis', 'm-work'], ['full', 'about'], ['full', 'team'], ['full', 'work'], ['full', 'footer']],
  },

  smoothsail: {
    base: 'https://smoothsail.my/', device: 'narrow', boot: 4000,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'Your shop, open by the weekend — the hero' },
      { id: 'mock', steps: [['y', 520]], alt: 'A real storefront running on SmoothSail, framed in the hero' },
      { id: 'parts', steps: [['to', 'text=The parts of selling', 0.1]], alt: 'The parts of selling that nobody enjoys' },
      { id: 'bento', steps: [['to', 'text=The parts of selling', 0.1], ['wheel', 400, 1]], alt: 'Delivery, stock, themes and numbers as live interface' },
      { id: 'why', steps: [['to', 'text=We tell you', 0.12]], alt: 'We tell you why, not just that' },
      { id: 'domain', focus: [0.3, 0.5], steps: [['to', 'text=A shop on your own', 0.2]], alt: 'A shop on your own address, desktop and phone' },
      { id: 'orders', steps: [['to', 'text=Paid and packed', 0.2]], alt: 'Paid and packed are two different questions — the orders view' },
      { id: 'malaysian', steps: [['to', 'text=Malaysian by default', 0.12]], alt: 'Malaysian by default, not by plugin' },
      { id: 'pricing', steps: [['to', 'text=Everything is in the', 0.12]], alt: 'Pricing' },
      { id: 'thirty', steps: [['to', 'text=Thirty days', 0.2]], alt: 'Thirty days, no card, your own shop at the end of it' },
      { id: 'ms', focus: [0.5, 0.5], url: '/ms', steps: [['wait', 1000]], alt: 'The site in Bahasa Melayu' },
      { id: 'store', url: 'https://teluk-ceramics.smoothsail.my/', steps: [['wait', 2000]], alt: 'Teluk Ceramics, a live store built on SmoothSail' },
      { id: 'store2', url: 'https://teluk-ceramics.smoothsail.my/', steps: [['wheel', 400, 2]], alt: 'Teluk Ceramics: the collection' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-products', device: P, steps: [['y', 804]], alt: 'Phone: the storefront in the hero' },
      { id: 'm-numbers', device: P, steps: [['to', 'text=Numbers you can act on', 0.5]], alt: 'Phone: numbers you can act on' },
      { id: 'm-orders', device: P, steps: [['to', 'text=Paid and packed', 0.05], ['wheel', 300, 2]], alt: 'Phone: the orders view' },
      { id: 'm-thirty', device: P, steps: [['to', 'text=Thirty days', 0.3]], alt: 'Phone: thirty days' },
      { id: 'm-store', device: P, url: 'https://teluk-ceramics.smoothsail.my/', steps: [['wait', 2000]], alt: 'Phone: the live store' },
      { id: 'm-store2', device: P, url: 'https://teluk-ceramics.smoothsail.my/', steps: [['wheel', 400, 2]], alt: 'Phone: the live store’s collection' },
    ],
    cover: 'hero',
    rows: [['full', 'mock'], ['pair', 'ms', 'domain'], ['trio', 'm-hero', 'm-products', 'm-orders'], ['full', 'parts'], ['full', 'orders'], ['full', 'why'], ['full', 'malaysian'], ['full', 'thirty']],
  },

  'big-brain-furniture': {
    base: 'https://bbf.lewix.ai/', device: 'wide', boot: 5000, settle: 3000, init: EAGER,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'Old Wood, New Life — the hero' },
      { id: 'releases', steps: [['y', 900]], alt: 'New releases: reclaimed teak pieces' },
      { id: 'categories', steps: [['y', 1350]], alt: 'Explore all categories' },
      { id: 'danga', steps: [['y', 2250]], settle: 4500, alt: 'Project spotlight: Danga Sutera' },
      { id: 'dining', steps: [['y', 3600]], alt: 'The reclaimed teak dining room' },
      { id: 'journal', steps: [['y', 4500]], alt: 'From the journal' },
      { id: 'catalogues', steps: [['y', 5400]], alt: 'Catalogues' },
      { id: 'collection', url: '/collections/dining.html', steps: [['wait', 1000]], alt: 'A collection page: dining' },
      { id: 'collection2', url: '/collections/dining.html', steps: [['wheel', 450, 1]], alt: 'A collection page: the range' },
      { id: 'product', focus: [0.2, 0.5], url: '/products/lauren-reclaimed-teakwood-plate.html', steps: [['wait', 1000]], alt: 'A product page' },
      { id: 'projects', url: '/projects.html', steps: [['wait', 1000]], alt: 'The projects index' },
      { id: 'project', url: '/projects/danga-sutera.html', steps: [['wait', 1000]], alt: 'A project page: Danga Sutera' },
      { id: 'materials', focus: [0.3, 0.5], url: '/materials.html', steps: [['wait', 1000]], alt: 'The material index' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-categories', device: P, steps: [['y', 1206]], alt: 'Phone: categories' },
      { id: 'm-danga', device: P, steps: [['y', 2010]], settle: 4500, alt: 'Phone: Danga Sutera' },
      { id: 'm-dining', device: P, steps: [['y', 3216]], alt: 'Phone: the dining room' },
      { id: 'm-journal', device: P, steps: [['y', 4422]], alt: 'Phone: the journal' },
      { id: 'm-product', device: P, url: '/products/lauren-reclaimed-teakwood-plate.html', steps: [['wait', 1000]], alt: 'Phone: a product page' },
    ],
    cover: 'hero',
    rows: [['full', 'danga'], ['pair', 'product', 'materials'], ['trio', 'm-hero', 'm-danga', 'm-categories'], ['full', 'collection'], ['full', 'categories'], ['full', 'journal'], ['full', 'dining'], ['full', 'projects']],
  },

  'big-brain-furniture-alt': {
    base: 'https://ff-bbf-alt.pages.dev/', device: 'wide', boot: 5000, settle: 3000, init: EAGER,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'Crafted for Moments, Made for Gathering — the split hero' },
      { id: 'categories', steps: [['y', 900]], alt: 'Categories as tall photographs' },
      { id: 'oldwood', steps: [['y', 1350]], alt: 'Old Wood, New Life beside a slab of reclaimed teak' },
      { id: 'table', steps: [['y', 2250]], alt: 'On the Table: reclaimed teak serving pieces' },
      { id: 'storage', steps: [['y', 3150]], alt: 'Storage That Earns Its Wall' },
      { id: 'imperfection', focus: [0.75, 0.5], steps: [['y', 4950]], alt: 'Guided by Imperfection' },
      { id: 'rooms', steps: [['y', 5850]], alt: 'Shop by room' },
      { id: 'collection', url: '/collections/sofa.html', steps: [['wait', 1000]], alt: 'A collection page: sofas' },
      { id: 'room', url: '/rooms/dining-room.html', steps: [['wait', 1000]], alt: 'A room page: the dining room' },
      { id: 'product', focus: [0.35, 0.5], url: '/products/giselle-tray.html', steps: [['wait', 1000]], alt: 'A product page' },
      { id: 'project', url: '/projects/eco-botanic.html', steps: [['wait', 1000]], alt: 'A project page' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-1', device: P, steps: [['y', 1206]], alt: 'Phone: Old Wood, New Life over a slab of reclaimed teak' },
      { id: 'm-2', device: P, steps: [['y', 2010]], alt: 'Phone' },
      { id: 'm-3', device: P, steps: [['y', 3216]], alt: 'Phone' },
      { id: 'm-4', device: P, steps: [['y', 4422]], alt: 'Phone: Guided by Imperfection' },
      { id: 'm-5', device: P, steps: [['y', 5628]], alt: 'Phone' },
      { id: 'm-product', device: P, url: '/products/giselle-tray.html', steps: [['wait', 1000]], alt: 'Phone: a product page' },
    ],
    cover: 'hero',
    rows: [['full', 'categories'], ['pair', 'product', 'imperfection'], ['trio', 'm-hero', 'm-1', 'm-4'], ['full', 'oldwood'], ['full', 'table'], ['full', 'storage'], ['full', 'collection'], ['full', 'rooms']],
  },

  'ascend-peptides': {
    base: 'https://ascendpeptides.my/', device: 'narrow', boot: 4000, settle: 2500, init: EAGER,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'Premium Research Peptides in Malaysia — the hero' },
      { id: 'feature', steps: [['y', 806]], settle: 1200, alt: 'The featured compound: vial, specification and price' },
      { id: 'categories', steps: [['to', 'text=Shop by Category', 0.1]], alt: 'Shop by category' },
      { id: 'featured', steps: [['to', 'text=Featured Products', 0.1]], alt: 'Featured products' },
      { id: 'products', url: '/products', steps: [['wait', 1000]], alt: 'The catalogue' },
      { id: 'product', url: '/products/ghk-cu-100mg', steps: [['wait', 1000]], alt: 'A product page: specification first' },
      { id: 'product2', url: '/products/ghk-cu-100mg', steps: [['wheel', 400, 2]], alt: 'A product page: documentation and storage' },
      { id: 'calculator', url: '/calculator', steps: [['wait', 1000]], alt: 'The reconstitution calculator' },
      { id: 'coa', url: '/coa', steps: [['wait', 1000]], alt: 'Certificates of analysis' },
      { id: 'guide', url: '/guide', steps: [['wait', 1000]], alt: 'The peptide guide' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-vial', device: P, steps: [['to', 'text=GHK-Cu 100mg', 0.5]], alt: 'Phone: verified purity, and the featured compound’s price' },
      { id: 'm-dark', device: P, steps: [['to', 'text=Verified Purity', 0.3]], alt: 'Phone: verified purity' },
      { id: 'm-grid', device: P, steps: [['to', 'text=Featured Products', 0.05], ['wheel', 300, 1]], alt: 'Phone: the product grid' },
      { id: 'm-product', device: P, url: '/products/ghk-cu-100mg', steps: [['wait', 1000]], alt: 'Phone: a product page' },
      { id: 'm-calculator', device: P, url: '/calculator', steps: [['wait', 1000]], alt: 'Phone: the calculator' },
    ],
    cover: 'hero',
    rows: [['full', 'product'], ['full', 'feature'], ['trio', 'm-hero', 'm-vial', 'm-product'], ['full', 'featured'], ['full', 'categories'], ['full', 'calculator'], ['full', 'product2']],
  },

  'lewix-my': {
    base: 'https://lewix.my/', device: 'narrow', boot: 4000,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], settle: 6000, alt: 'Software your business runs on — the hero over a live dashboard' },
      { id: 'dashboard', steps: [['y', 400]], settle: 6000, alt: 'The dashboard in the hero' },
      { id: 'two', steps: [['to', 'text=Two ways to work', 0.2]], alt: 'Two ways to work with us' },
      { id: 'system', focus: [0.2, 0.6], steps: [['to', 'text=One system your whole', 0.2]], alt: 'One system your whole operation runs on' },
      { id: 'horizon', steps: [['to', 'text=A publishing platform', 0.2]], alt: 'Horizon: where is software and AI going?' },
      { id: 'store', steps: [['to', 'text=A store builder', 0.2]], alt: 'SmoothSail: a store builder for the way Malaysia actually sells' },
      { id: 'integrations', focus: [0.72, 0.5], steps: [['to', 'text=Or start from what', 0.2]], alt: 'Or start from what you already run — integrations on dark' },
      { id: 'build', steps: [['to', 'text=How we build', 0.2]], alt: 'How we build' },
      { id: 'footer', steps: [['y', 99999]], alt: 'The footer' },
      { id: 'work', url: '/work/packaging-supplies-mis', steps: [['wait', 1000]], alt: 'A case study: packaging supplies MIS' },
      { id: 'work2', url: '/work/packaging-supplies-mis', steps: [['wheel', 400, 2]], alt: 'A case study, further down' },
      { id: 'services', url: '/services', steps: [['wait', 1000]], alt: 'Services' },
      { id: 'product', url: '/products/smoothsail', steps: [['wait', 1000]], alt: 'A product page: SmoothSail' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-system', device: P, steps: [['to', 'text=One system your whole', 0.2]], alt: 'Phone: one system' },
      { id: 'm-horizon', device: P, steps: [['to', 'text=A publishing platform', 0.2]], alt: 'Phone: Horizon' },
      { id: 'm-store', device: P, steps: [['to', 'text=A store builder', 0.2]], alt: 'Phone: SmoothSail' },
      { id: 'm-integrations', device: P, steps: [['to', 'text=Or start from what', 0.2]], alt: 'Phone: integrations' },
    ],
    cover: 'hero',
    rows: [['full', 'dashboard'], ['full', 'horizon'], ['pair', 'system', 'integrations'], ['trio', 'm-hero', 'm-horizon', 'm-integrations'], ['full', 'store'], ['full', 'build'], ['full', 'footer']],
  },

  'basement-translation': {
    base: 'https://ff-concepts.pages.dev/concepts/01/', device: 'wide', boot: 4000,
    shots: [
      { id: 'hero', steps: [['wait', 1500]], alt: 'The hero: a line drawing on black' },
      { id: 'talk', steps: [['y', 900]], alt: 'You talk to the person who builds it.' },
      { id: 'work', steps: [['y', 1350]], alt: 'Selected work' },
      { id: 'work-hover', steps: [['y', 1350]], cursor: [0.75, 0.55], alt: 'Selected work, one row under the cursor' },
      { id: 'capabilities', steps: [['y', 3600]], alt: 'Capabilities' },
      { id: 'ways', steps: [['y', 4500]], alt: 'Ways in: the three builds and their prices' },
      { id: 'end', steps: [['y', 99999]], alt: 'Let’s build something.' },
      { id: 'm-hero', device: P, steps: [['wait', 1500]], alt: 'Phone: the hero' },
      { id: 'm-1', device: P, steps: [['y', 402]], alt: 'Phone: You talk to the person who builds it.' },
      { id: 'm-2', device: P, steps: [['y', 1206]], alt: 'Phone' },
      { id: 'm-3', device: P, steps: [['y', 2412]], alt: 'Phone' },
      { id: 'm-4', device: P, steps: [['y', 3618]], alt: 'Phone: capabilities, numbered' },
      { id: 'm-5', device: P, steps: [['y', 4824]], alt: 'Phone: the Showpiece build and its price' },
    ],
    cover: 'talk',
    rows: [['full', 'hero'], ['full', 'capabilities'], ['trio', 'm-1', 'm-4', 'm-5'], ['full', 'ways'], ['full', 'end']],
  },

  'ff-shoots': {
    base: 'https://ff-shoots.pages.dev/', device: 'wide', boot: 6000,
    init: [['click', 'text=enter without'], ['wait', 4000]],
    shots: [
      { id: 'slider', steps: [['wait', 500]], alt: 'The slider' },
      { id: 'slider2', steps: [['wheel', 250, 1], ['wait', 1500]], alt: 'The slider' },
      { id: 'slider3', steps: [['wheel', 250, 3], ['wait', 1500]], alt: 'The slider' },
      { id: 'fisheye', steps: [['click', 'button.fisheye-toggle'], ['wait', 1500]], alt: 'The slider through the fisheye lens' },
      { id: 'fisheye2', steps: [['wheel', 250, 2], ['wait', 1500]], alt: 'The fisheye lens' },
      { id: 'grid', steps: [['click', 'button.fisheye-toggle'], ['click', 'text=grid'], ['wait', 2500]], alt: 'Grid view' },
      { id: 'grid2', steps: [['wheel', 400, 2], ['wait', 1500]], alt: 'Grid view' },
      { id: 'list', steps: [['click', 'text=list'], ['wait', 2500]], alt: 'List view' },
      { id: 'list-hover', steps: [], cursor: [0.5, 0.45], alt: 'List view with a row under the cursor' },
      { id: 'about', url: '/about', steps: [['wait', 2000]], alt: 'About' },
      { id: 'about2', url: '/about', steps: [['wheel', 400, 2]], alt: 'About' },
      { id: 'm-slider', device: P, steps: [['wait', 500]], alt: 'Phone: the slider' },
      { id: 'm-slider2', device: P, steps: [['drag', [0.8, 0.5, 0.2, 0.5]], ['wait', 1500]], alt: 'Phone: the slider' },
      { id: 'm-slider3', device: P, steps: [['drag', [0.8, 0.5, 0.2, 0.5]], ['wait', 800], ['drag', [0.8, 0.5, 0.2, 0.5]], ['wait', 1500]], alt: 'Phone: the slider' },
      { id: 'project', steps: [['tap', 0.5, 0.5], ['wait', 4000]], alt: 'A project opened from the slider' },
      { id: 'project2', steps: [['wheel', 400, 2], ['wait', 2000]], alt: 'A project, further in' },
    ],
    cover: 'slider',
    rows: [['full', 'grid'], ['pair', 'fisheye', 'slider3'], ['trio', 'm-slider', 'm-slider2', 'm-slider3'], ['full', 'project'], ['full', 'about']],
  },

  'ff-frames': {
    base: 'https://ff-frames.pages.dev/', device: 'wide', boot: 6000, settle: 2500,
    shots: [
      { id: 'home', steps: [['wait', 500]], alt: 'The index over a full-bleed photograph' },
      { id: 'home-w', steps: [], cursor: [0.28, 0.17], alt: 'Weddings under the cursor' },
      { id: 'home-e', steps: [], cursor: [0.35, 0.4], alt: 'Engagements under the cursor' },
      { id: 'home-c', steps: [], cursor: [0.3, 0.56], alt: 'Commercial under the cursor' },
      { id: 'home-ed', steps: [], cursor: [0.33, 0.72], alt: 'Editorials under the cursor' },
      { id: 'weddings', url: '/weddings', steps: [['wait', 1000]], alt: 'Weddings' },
      { id: 'weddings2', url: '/weddings', steps: [['wheel', 450, 2]], alt: 'Weddings' },
      { id: 'weddings3', url: '/weddings', steps: [['wheel', 450, 3]], alt: 'Weddings' },
      { id: 'stories', url: '/stories', steps: [['wait', 1000]], alt: 'Stories' },
      { id: 'stories2', url: '/stories', steps: [['wheel', 450, 2]], alt: 'Stories' },
      { id: 'engagements', url: '/engagements', steps: [['wait', 1000]], alt: 'Engagements' },
      { id: 'commercial', url: '/commercial', steps: [['wait', 1000]], alt: 'Commercial' },
      { id: 'editorials', url: '/editorials', steps: [['wait', 1000]], alt: 'Editorials' },
      { id: 'exchange', focus: [0.62, 0.5], url: '/editorials/exchange', steps: [['wait', 1000]], alt: 'Editorial exchange' },
      { id: 'exchange2', url: '/editorials/exchange', steps: [['wheel', 450, 2]], alt: 'Editorial exchange' },
      { id: 'pricing', url: '/pricing', steps: [['wait', 1000]], alt: 'Pricing' },
      { id: 'pricing2', url: '/pricing', steps: [['wheel', 450, 2]], alt: 'Pricing' },
      { id: 'pricing3', url: '/pricing', steps: [['wheel', 450, 2]], alt: 'Pricing' },
      { id: 'about', url: '/about', steps: [['wait', 1000]], alt: 'About' },
      { id: 'about2', url: '/about', steps: [['wheel', 450, 2]], alt: 'About' },
      { id: 'm-home', device: P, steps: [['wait', 500]], alt: 'Phone: the index' },
      { id: 'm-weddings', device: P, url: '/weddings', steps: [['wait', 1000]], alt: 'Phone: weddings' },
      { id: 'm-weddings2', device: P, url: '/weddings', steps: [['wheel', 400, 2]], alt: 'Phone: weddings' },
      { id: 'm-stories', device: P, url: '/stories', steps: [['wait', 1000]], alt: 'Phone: stories' },
      { id: 'm-pricing', device: P, url: '/pricing', steps: [['wheel', 400, 2]], alt: 'Phone: pricing' },
      { id: 'm-exchange', device: P, url: '/editorials/exchange', steps: [['wait', 1000]], alt: 'Phone: editorial exchange' },
    ],
    cover: 'weddings',
    rows: [['full', 'home-w'], ['pair', 'engagements', 'exchange'], ['trio', 'm-home', 'm-weddings', 'm-exchange'], ['full', 'exchange2'], ['full', 'commercial'], ['full', 'stories2'], ['full', 'weddings3'], ['full', 'about'], ['full', 'pricing']],
  },

  meridian: {
    // shot on ffdev.studio, the engine in production with FF's own work (ff-meridian.pages.dev is the placeholder reference build)
    base: 'https://ffdev.studio/', device: 'wide', boot: 9000,
    shots: [
      { id: 'strip', steps: [['wait', 500]], alt: 'The project strip' },
      { id: 'strip2', steps: [['wheel', 300, 4], ['wait', 1800]], alt: 'The strip, moving' },
      { id: 'strip3', steps: [['wheel', 300, 6], ['wait', 1800]], alt: 'The strip' },
      { id: 'strip-hover', steps: [], cursor: [0.5, 0.5], alt: 'A project under the cursor' },
      { id: 'strip4', steps: [['wheel', 300, 10], ['wait', 1800]], alt: 'The strip' },
      { id: 'search', url: '/ff-search', steps: [['wait', 3000]], alt: 'A project opened: FF Search' },
      { id: 'search2', url: '/ff-search', steps: [['wheel', 400, 3], ['wait', 1800]], alt: 'FF Search, further in' },
      { id: 'shoots', url: '/ff-shoots', steps: [['wait', 3000]], alt: 'A project opened: FF Shoots' },
      { id: 'stanzza', url: '/ff-stanzza', steps: [['wait', 3000]], alt: 'A project opened: FF Stanzza' },
      { id: 'about', focus: [0.22, 0.5], url: '/about', steps: [['wait', 3000]], alt: 'About' },
      { id: 'pricing', focus: [0.3, 0.5], url: '/pricing', steps: [['wait', 3000]], alt: 'Pricing' },
      { id: 'm-strip', device: P, steps: [['wait', 500]], alt: 'Phone: the index' },
      { id: 'm-strip2', device: P, steps: [['drag', [0.5, 0.75, 0.5, 0.25]], ['wait', 1800]], alt: 'Phone: the index' },
      { id: 'm-project', device: P, url: '/ff-search', steps: [['wait', 3000]], alt: 'Phone: a project' },
      { id: 'm-project2', device: P, url: '/ff-search', steps: [['wheel', 400, 2], ['wait', 1800]], alt: 'Phone: a project' },
      { id: 'm-about', device: P, url: '/about', steps: [['wait', 3000]], alt: 'Phone: about' },
    ],
    cover: 'search',
    rows: [['full', 'strip-hover'], ['pair', 'about', 'pricing'], ['trio', 'm-strip', 'm-project', 'm-about'], ['full', 'shoots'], ['full', 'stanzza'], ['full', 'strip4']],
  },

  'obys-translation': {
    base: 'https://ff-concepts.pages.dev/concepts/02/', device: 'mid', boot: 5000,
    shots: [
      { id: 'vertical', steps: [['wait', 500]], alt: 'Vertical layout' },
      { id: 'vertical2', steps: [['wheel', 300, 3], ['wait', 1500]], alt: 'Vertical layout, scrolled' },
      { id: 'vertical-hover', steps: [], cursor: [0.5, 0.5], alt: 'Vertical, a card under the cursor' },
      { id: 'horizontal', steps: [['click', 'text=Horizontal'], ['wait', 3000]], alt: 'Horizontal layout' },
      { id: 'horizontal2', steps: [['wheel', 300, 3], ['wait', 1500]], alt: 'Horizontal layout, scrolled' },
      { id: 'flip', steps: [['click', 'text=Grid'], ['wait', 450]], settle: 0, alt: 'Mid-flip between layouts' },
      { id: 'grid', steps: [['wait', 3000]], alt: 'Grid layout' },
      { id: 'grid-hover', steps: [['mouse', 0.3, 0.5]], cursor: [0.16, 0.7], alt: 'Grid, a card under the cursor' },
      { id: 'm-vertical', device: P, steps: [['wait', 500]], alt: 'Phone: vertical' },
      { id: 'm-horizontal', device: P, steps: [['click', 'text=Horizontal'], ['wait', 3000]], alt: 'Phone: horizontal' },
      { id: 'm-grid', device: P, steps: [['click', 'text=Grid'], ['wait', 3000]], alt: 'Phone: grid' },
    ],
    cover: 'grid-hover',
    rows: [['full', 'horizontal2'], ['full', 'vertical-hover'], ['full', 'vertical2']],
  },
};
